// Dalton's Tonies collection
// Public catalog data only — no purchase prices, order numbers, or gift-card details.
// Add future Tonies to this array and the page will pick them up automatically.

window.daltonTonies = [
  {
    id: "lilo-stitch",
    name: "Stitch",
    officialName: "Disney Lilo & Stitch Tonie",
    displayTitle: "Lilo & Stitch",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "29 min",
    content: "Adventure & songs",
    image: "images/tonies/lilo-stitch.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Lilo--Stitch-10000936-TB2Hero2.png?width=1200",
    featured: true
  },
  {
    id: "simba-cuddle",
    name: "Simba Cuddle",
    officialName: "Disney Simba Cuddle Tonie",
    displayTitle: "The Lion King",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "36 min",
    content: "Calming stories & sounds",
    image: "images/tonies/simba-cuddle.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Cuddle-Simba-11003866-TB2Hero2.png?width=1200",
    featured: true
  },
  {
    id: "vampire-creative",
    name: "Vampire",
    officialName: "Vampire Creative Tonie",
    brand: "Creative Tonies",
    category: "Creative",
    type: "creative",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "Up to 90 min",
    content: "Your own audio",
    image: "images/tonies/vampire-creative.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Vampire-10000547-TB2Hero2.png?width=1200",
    featured: true
  },
  {
    id: "dorothy-dinosaur",
    name: "Dorothy the Dinosaur",
    officialName: "The Wiggles: Dorothy The Dinosaur Tonie",
    brand: "The Wiggles",
    category: "Kids & Learning",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "42 min",
    content: "Songs, movement & education",
    image: "images/tonies/dorothy-dinosaur.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Dorothy-The-Dinosaur-11004232-TB2Hero2.png?width=1200",
    featured: true
  },
  {
    id: "pokemon-pikachu",
    name: "Pikachu",
    generation: "Gen 1",
    displayTitle: "Pokémon Adventure",
    officialName: "Pokémon Pikachu Tonie",
    brand: "Pokémon",
    category: "Pokémon",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "5+",
    runtime: "78 min",
    content: "Mysteries, Trainer Academy facts & a Pokémon battle",
    image: "images/tonies/pokemon-pikachu.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Pikachu-11000561-TB2Hero2.png?width=1200",
    featured: true
  },
  {
    id: "pokemon-bulbasaur",
    name: "Bulbasaur",
    generation: "Gen 1",
    displayTitle: "Pokémon Adventure",
    officialName: "Pokémon Bulbasaur Tonie",
    brand: "Pokémon",
    category: "Pokémon",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "5+",
    runtime: "77 min",
    content: "Clever adventures, Trainer Academy facts & a Pokémon battle",
    image: "images/tonies/pokemon-bulbasaur.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Bulbasaur-11003603-TB2Hero2.png?width=1200",
    featured: true
  },
  {
    id: "pokemon-charmander",
    name: "Charmander",
    generation: "Gen 1",
    displayTitle: "Pokémon Adventure",
    officialName: "Pokémon Charmander Tonie",
    brand: "Pokémon",
    category: "Pokémon",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "5+",
    runtime: "79 min",
    content: "Fiery adventures, Trainer Academy facts & a Pokémon battle",
    image: "images/tonies/pokemon-charmander.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Charmander-11003600-TB2Hero2.png?width=1200",
    featured: true
  },
  {
    id: "pokemon-squirtle",
    name: "Squirtle",
    generation: "Gen 1",
    displayTitle: "Pokémon Adventure",
    officialName: "Pokémon Squirtle Tonie",
    brand: "Pokémon",
    category: "Pokémon",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "5+",
    runtime: "67 min",
    content: "Seaside adventures, Trainer Academy facts & a Pokémon battle",
    image: "images/tonies/pokemon-squirtle.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Squirtle-11003602-TB2Hero2.png?width=1200",
    featured: true
  },
  {
    id: "hercules",
    name: "Hercules",
    officialName: "Disney Hercules Tonie",
    displayTitle: "Hercules",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "5+",
    runtime: "47 min",
    content: "Adventure & sing-along",
    image: "images/tonies/hercules.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Hercules-10001698-TB2Hero2.png?width=1200"
  },
  {
    id: "jungle-book",
    name: "Baloo",
    officialName: "Disney The Jungle Book Tonie",
    displayTitle: "The Jungle Book",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "15–30 min",
    content: "Adventure & songs",
    image: "images/tonies/jungle-book.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/The-Jungle-Book-10000497-TB2Hero2.png?width=1200"
  },
  {
    id: "monsters-inc",
    name: "Sulley",
    officialName: "Disney and Pixar Monsters, Inc. Tonie",
    displayTitle: "Monsters, Inc.",
    brand: "Disney & Pixar",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "5+",
    runtime: "33 min",
    content: "Adventure & songs",
    image: "images/tonies/monsters-inc.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Monsters_-Inc.-10000517-TB2Hero1.png?width=1200"
  },
  {
    id: "mickey-mouse-clubhouse",
    name: "Mickey Mouse",
    officialName: "Disney Mickey Mouse Clubhouse Tonie",
    displayTitle: "Mickey Mouse Clubhouse",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "1+",
    runtime: "38 min",
    content: "Adventure & songs",
    image: "images/tonies/mickey-mouse-clubhouse.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Mickey-Clubhouse-10001072-TB2Hero2.png?width=1200"
  },
  {
    id: "woody",
    name: "Woody",
    officialName: "Disney and Pixar Toy Story: Woody Tonie",
    displayTitle: "Toy Story",
    brand: "Disney & Pixar",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "",
    content: "Toy Story",
    image: "images/tonies/woody.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Woody-10000511-TB2Hero2.png?width=1200"
  },
  {
    id: "ms-rachel",
    name: "Ms. Rachel",
    officialName: "Ms. Rachel Tonie",
    brand: "Ms. Rachel",
    category: "Kids & Learning",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "1+",
    runtime: "About 50 min",
    content: "Songs & learning",
    image: "images/tonies/ms-rachel.png",
    remoteImage: "https://tonies.com.au/cdn/shop/files/Ms-Rachel-11002272-TB2Hero1.png?width=1200"
  },
  {
    id: "cookie-monster",
    name: "Cookie Monster",
    officialName: "Sesame Street: Cookie Monster Tonie",
    brand: "Sesame Street",
    category: "Sesame Street",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "30–45 min",
    content: "Healthy habits, education & songs",
    image: "images/tonies/cookie-monster.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Cookie-Monster-10000630-TB2Hero2.png?width=1200"
  },
  {
    id: "blues-clues",
    name: "Blue's Clues & You!",
    officialName: "Blue’s Clues & You Tonie",
    brand: "Blue's Clues & You!",
    category: "Kids & Learning",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "57 min",
    content: "Learning, problem-solving & songs",
    image: "images/tonies/blues-clues.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/Blue_s-Clues-10000777-TB2Hero2.png?width=1200"
  },
  {
    id: "nightmare-before-christmas",
    name: "Jack Skellington",
    officialName: "Disney The Nightmare Before Christmas Tonie",
    displayTitle: "The Nightmare Before Christmas",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "6+",
    runtime: "47 min",
    content: "Story & songs",
    image: "images/tonies/nightmare-before-christmas.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/The-Nightmare-Before-Christmas-10001358-TB2Hero2.png?width=1200"
  },
  {
    id: "lion-king",
    name: "Simba",
    officialName: "Disney The Lion King Tonie",
    displayTitle: "The Lion King",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "30–45 min",
    content: "Story & songs",
    image: "images/tonies/lion-king.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/The-Lion-King-10000498-TB2Hero2.png?width=1200"
  },
  {
    id: "incredibles",
    name: "Mr. Incredible",
    officialName: "Disney and Pixar The Incredibles Tonie",
    displayTitle: "The Incredibles",
    brand: "Disney & Pixar",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "6+",
    runtime: "60+ min",
    content: "Adventure",
    image: "images/tonies/incredibles.png",
    remoteImage: "https://us.tonies.com/cdn/shop/files/The-Incredibles-10001301-TB2Hero2.png?width=1200"
  }
];

const daltonToniebox = {
  name: "Toniebox 2",
  color: "Lightning Yellow",
  acquired: "October 7, 2026",
  source: "Pokémon Toniebox 2 Starter Set"
};
