// Dalton's Tonies collection
// Public catalog data only — no purchase prices, order numbers, or gift-card details.
// Add future Tonies to this array and the page will pick them up automatically.

const daltonTonies = [
  {
    id: "lilo-stitch",
    name: "Stitch",
    officialName: "Disney Lilo & Stitch Tonie",
    displayTitle: "Lilo & Stitch",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "29 min",
    content: "Adventure & songs",
    image: "",
    featured: true
  },
  {
    id: "simba-cuddle",
    name: "Simba Cuddle",
    officialName: "Disney Simba Cuddle Tonie",
    displayTitle: "The Lion King",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "36 min",
    content: "Calming stories & sounds",
    image: "",
    featured: true
  },
  {
    id: "vampire-creative",
    name: "Vampire",
    officialName: "Vampire Creative Tonie",
    brand: "Creative Tonies",
    category: "Creative",
    type: "creative",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "Up to 90 min",
    content: "Your own audio",
    image: "",
    featured: true
  },
  {
    id: "dorothy-dinosaur",
    name: "Dorothy the Dinosaur",
    officialName: "The Wiggles: Dorothy The Dinosaur Tonie",
    brand: "The Wiggles",
    category: "Kids & Learning",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "42 min",
    content: "Songs, movement & education",
    image: "",
    featured: true
  },
  {
    id: "pokemon-pikachu",
    name: "Pikachu",
    displayTitle: "Pokémon",
    officialName: "Pokémon Pikachu Tonie",
    brand: "Pokémon",
    category: "Pokémon",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "",
    runtime: "",
    content: "Pokémon",
    image: "",
    featured: true
  },
  {
    id: "pokemon-bulbasaur",
    name: "Bulbasaur",
    displayTitle: "Pokémon",
    officialName: "Pokémon Bulbasaur Tonie",
    brand: "Pokémon",
    category: "Pokémon",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "",
    runtime: "",
    content: "Pokémon",
    image: "",
    featured: true
  },
  {
    id: "pokemon-charmander",
    name: "Charmander",
    displayTitle: "Pokémon",
    officialName: "Pokémon Charmander Tonie",
    brand: "Pokémon",
    category: "Pokémon",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "",
    runtime: "",
    content: "Pokémon",
    image: "",
    featured: true
  },
  {
    id: "pokemon-squirtle",
    name: "Squirtle",
    displayTitle: "Pokémon",
    officialName: "Pokémon Squirtle Tonie",
    brand: "Pokémon",
    category: "Pokémon",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "",
    runtime: "",
    content: "Pokémon",
    image: "",
    featured: true
  },
  {
    id: "hercules",
    name: "Hercules",
    officialName: "Disney Hercules Tonie",
    displayTitle: "Hercules",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "5+",
    runtime: "47 min",
    content: "Adventure & sing-along",
    image: ""
  },
  {
    id: "jungle-book",
    name: "Baloo",
    officialName: "Disney The Jungle Book Tonie",
    displayTitle: "The Jungle Book",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "15–30 min",
    content: "Adventure & songs",
    image: ""
  },
  {
    id: "monsters-inc",
    name: "Sulley",
    officialName: "Disney and Pixar Monsters, Inc. Tonie",
    displayTitle: "Monsters, Inc.",
    brand: "Disney & Pixar",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "5+",
    runtime: "33 min",
    content: "Adventure & songs",
    image: ""
  },
  {
    id: "mickey-mouse-clubhouse",
    name: "Mickey Mouse",
    officialName: "Disney Mickey Mouse Clubhouse Tonie",
    displayTitle: "Mickey Mouse Clubhouse",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "1+",
    runtime: "38 min",
    content: "Adventure & songs",
    image: ""
  },
  {
    id: "woody",
    name: "Woody",
    officialName: "Disney and Pixar Toy Story: Woody Tonie",
    displayTitle: "Toy Story",
    brand: "Disney & Pixar",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "",
    content: "Toy Story",
    image: ""
  },
  {
    id: "ms-rachel",
    name: "Ms. Rachel",
    officialName: "Ms. Rachel Tonie",
    brand: "Ms. Rachel",
    category: "Kids & Learning",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "1+",
    runtime: "About 50 min",
    content: "Songs & learning",
    image: ""
  },
  {
    id: "cookie-monster",
    name: "Cookie Monster",
    officialName: "Sesame Street: Cookie Monster Tonie",
    brand: "Sesame Street",
    category: "Sesame Street",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "30–45 min",
    content: "Healthy habits, education & songs",
    image: ""
  },
  {
    id: "blues-clues",
    name: "Blue's Clues & You!",
    officialName: "Blue’s Clues & You Tonie",
    brand: "Blue's Clues & You!",
    category: "Kids & Learning",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "57 min",
    content: "Learning, problem-solving & songs",
    image: ""
  },
  {
    id: "nightmare-before-christmas",
    name: "Jack Skellington",
    officialName: "Disney The Nightmare Before Christmas Tonie",
    displayTitle: "The Nightmare Before Christmas",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "6+",
    runtime: "47 min",
    content: "Story & songs",
    image: ""
  },
  {
    id: "lion-king",
    name: "Simba",
    officialName: "Disney The Lion King Tonie",
    displayTitle: "The Lion King",
    brand: "Disney",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "3+",
    runtime: "30–45 min",
    content: "Story & songs",
    image: ""
  },
  {
    id: "incredibles",
    name: "Mr. Incredible",
    officialName: "Disney and Pixar The Incredibles Tonie",
    displayTitle: "The Incredibles",
    brand: "Disney & Pixar",
    category: "Disney",
    type: "content",
    status: "owned",
    acquired: "October 7, 2026",
    age: "6+",
    runtime: "60+ min",
    content: "Adventure",
    image: ""
  }
];

const daltonToniebox = {
  name: "Toniebox 2",
  color: "Lightning Yellow",
  acquired: "October 7, 2026",
  source: "Pokémon Toniebox 2 Starter Set"
};
